name: 🆕 New Release (Build + Deploy)

on:
  workflow_dispatch:

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3
        
      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: 💾 Install dependencies
        run: yarn install

      - name: 🔄 Run Expo Prebuild
        run: npx expo prebuild -p android
  
      - name: ⚙️ Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
  
      - name: 🚀 Build Debug APK
        run: |
          cd android
          ./gradlew ":app:assembleRelease"
          ls app/build/outputs/apk/release/
  
      - name: 🛠️ Rename APK files
        run: |
          cd android/app/build/outputs/apk/release/
          for file in *.apk; do
            mv "$file" "Papillon Dev-${file%-debug.apk}.apk"
          done
  
      - name: 🛜 Upload Debug APKs
        uses: actions/upload-artifact@v4
        with:
          name: debug-apks
          path: android/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
